
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvisbbxohzsqkkoxxpbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52aXNiYnhvaHpzcWtrb3h4cGJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0OTc1NzEsImV4cCI6MjA1OTA3MzU3MX0.9dqgzQ8iLV3wfIzKwes0eMyr5ZsBRLb00qC30tcW-6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
